### ISSUE TITLE
Open file descriptors metric on MacOS

### ISSUE THREAD

**Issue by xamgore** [siimon/prom-client#378] opened 2020-07-08 11:42 UTC
As you may find in the [source code](https://github.com/siimon/prom-client/blob/4e6aacd4921a3791e8f01ac6ab2fd6bb421b0dc0/lib/metrics/processOpenFileDescriptors.js#L10), the current metric implementation ignores non-linux systems:

```js
if (process.platform !== 'linux') return;
const fds = fs.readdirSync('/proc/self/fd');
```

On macos `/dev/fd` may be used instead. From [MacOS X internals book](http://newosxbook.com/MOXiI.pdf), the last sentence:

![image](https://user-images.githubusercontent.com/4586392/86914060-54931780-c128-11ea-9bbd-af0515928a4e.png)

> **`man mount_fdesc`**: `fd` is a directory whose contents appear as a list of numbered files which correspond to the open files of the process reading the directory. The files `/dev/fd/0` through `/dev/fd/#` refer to file descriptors which can be accessed through the file system.

May I make a PR?

**Comment by zbjornson** [comment] 2020-07-08 14:08
(#362)

PR definitely welcome!

**Comment by zbjornson** [comment] 2021-01-23 17:09
Closing as a dupe of #362.

**Closed by zbjornson** 2021-01-23 17:09 UTC
