### ISSUE TITLE
clusterServer undefined variable crash

### ISSUE THREAD

**Issue by antprogSmith** [siimon/prom-client#166] opened 2017-11-28 07:26 UTC
I'm using the latest version of prom client and nodejs v9.2
I copied the code in the prom-client example (clustered server) and use plain nodejs in the client in a clustered setup.

when calling the telemetry on the master node it crashes when the "request" is undefined.
This happens when the pending goes to zero.
By adding the line below it prevents the crash. 

---------------------------------------------------------------
node_modules/prom-client/lib/cluster.js
add the following line to 
"function addListeners() {"

         if (message.type === GET_METRICS_RES) {
            const request = requests.get(message.requestId);
            if (request){ **// MY FIX**
               ... put if statement the code..
            }

**Comment by zbjornson** [comment] 2017-11-28 07:57
Hm, I'm not sure I understand when this can happen and have never seen it myself. It looks like more responses for a particular request ID have to be received than expected, but I don't know how that could happen. Do you have any more info on reproducing this?

**Comment by antprogSmith** [comment] 2017-11-28 08:17
Here is the server code.

'use strict';
const http = require('http');
const client = require('prom-client');
const AggregatorRegistry = client.AggregatorRegistry;
const aggregatorRegistry = new AggregatorRegistry();

module.exports = (Config) => {
	const metrics = http.createServer(function (request, response) {
		request.on('data', (chunk) => {
		});

		request.on('end', () => {
			if (request.url === "/metrics") {
				try {
					aggregatorRegistry.clusterMetrics((err, metrics) => {
						if (err) console.log(err);
						response.writeHead(200, { 'Content-Type': client.register.contentType });
						response.end(metrics);
					});
				} catch (error) {
					console.log(error);
				}
			}
		});
	});
	metrics.listen(Config.port + 1);
	console.log(`METRICS Server running at ${metrics.address.name}:${Config.port + 1}/`);
}



--------------------------
client code..

async function startServer() {
	try {
        startTelemetry();
		await connections(Config);
	} catch (error) {
		console.log("Error connection to DB's", error);
	}

	loadVendors(Config);		// load all vendors into a global map(). Each instance has its own globals
	const server = http.createServer(function (request, response) {
		var data = '';

		request.on('data', (chunk) => {
			data += chunk;
		});

		request.on('end', () => {
			let payload;
			try {
				if (request.url !== "/" && request.url !== "/metrics") {
					sendError(response, {}, {}, 'Invalid URL');
				} else {
					if (request.url === "/metrics") {
						payload = {};
						response.writeHead(200, { 'Content-Type': client.register.contentType });
						response.end(client.register.metrics());
					} else if (request.method === "GET") {
						response.end('Welcome to AntSoftware: Switch');
					} else {
						let tel = global.telemetry.incoming.startRequest()
						payload = JSON.parse(data);
						send(payload, response)
							.then((result) => {
								response.end(JSON.stringify(result.result));
								global.telemetry.incoming.endRequest(tel);
							})
							.catch((err) => {
								global.telemetry.incoming.endRequest(tel);
								sendError(response, err, payload, 'General error.');
							});
					}
				}
			} catch (e) {
				sendError(response, e, payload, 'error parsing JSON message');
			}

		});
	});

	server.listen(Config.port);
	console.log(`Server running at ${server.address.name}:${Config.port}/`);

}

**Comment by zbjornson** [comment] 2017-11-28 16:09
Thanks. Two more questions...
- Where are you using node's cluster module? It's not shown in your example. I don't know what happens if you try to use the AggregatorRegistry without the cluster module.
- What does the client code do/where does it run/how are the "server" and "client" code sections related? It looks like both code sections set up HTTP servers and deliver Prometheus metrics, but I don't understand how they relate.

**Comment by antprogSmith** [comment] 2017-11-29 04:38
Perhaps this helps.
Here is the full app.js displaying how I create the cluster master and forks.
The line "	metricsServer(Config);		// use a metrics server"
creates the server which I pasted in previously as the "server code".
Hope this helps.



'use strict';
const Cluster = require('cluster');
const numCPUs = require('os').cpus().length;
const http = require('http');
const Config = require('./config.json');
const send = require('./sendMessages/send');
const loadVendors = require('../shared/DB/loadVendors');
const errorLog = require('../shared/DB/logs').errorLog;
const connections = require('./connections');
const client = require('prom-client');
const metricsServer = require('./metricsServer');
const startTelemetry = require('./telemetry');
const incomingTelemetry = require('../shared/telemetry/prometheus/switchIncoming');
const prometheus = require("../shared/telemetry/prometheus/prometheusWrapper");

startTelemetry();

if (Config.clusteredServer === true && Cluster.isMaster) {
	// Fork workers.
	for (let i = 0; i < numCPUs; i++) {
		Cluster.fork();
	}

	loadVendors(Config);		// load all vendors into a global map(). Each instance has its own globals
	metricsServer(Config);		// use a metrics server

	Cluster.on('exit', (worker, code, signal) => {
		console.log(`worker ${worker.process.pid} died`);
	});
} else {
	startServer();
}

async function startServer() {
	try {
		await connections(Config);
	} catch (error) {
		console.log("Error connection to DB's", error);
	}

	loadVendors(Config);		// load all vendors into a global map(). Each instance has its own globals
	const server = http.createServer(function (request, response) {
		var data = '';

		request.on('data', (chunk) => {
			data += chunk;
		});

		request.on('end', () => {
			let payload;
			try {
				if (request.url !== "/" && request.url !== "/metrics") {
					sendError(response, {}, {}, 'Invalid URL');
				} else {
					if (request.url === "/metrics") {
						payload = {};
						response.writeHead(200, { 'Content-Type': client.register.contentType });
						response.end(prometheus.getMetrics());
					} else if (request.method === "GET") {
						response.end('Welcome to AntSoftware: Switch');
					} else {
						let tel = incomingTelemetry.startRequest();
						payload = JSON.parse(data);
						send(payload, response)
							.then((result) => {
								response.end(JSON.stringify(result.result));
								incomingTelemetry.endRequest(tel);
							})
							.catch((err) => {
								incomingTelemetry.endRequest(tel);
								sendError(response, err, payload, 'General error.');
							});
					}
				}
			} catch (e) {
				sendError(response, e, payload, 'error parsing JSON message');
			}

		});
	});

	server.listen(Config.port);
	console.log(`Server running at ${server.address.name}:${Config.port}/`);

}


function sendError(response, err, payload, message, statusCode = 500) {
	incomingTelemetry.crash("app.js");
	errorLog(Config, message, err, payload);	// log error to DB

	err.message = message;
	response.statusCode = statusCode;
	response.statusMessage = message;
	response.end(JSON.stringify(err));
}

**Comment by zbjornson** [comment] 2017-11-29 18:29
Still having a bit of a hard time figuring out what's going on. Seeing what's in `"../shared/telemetry/prometheus/prometheusWrapper"` might help, but if you're able to remove as much code as possible while still reproducing the issue (i.e. minimal reproducible example), that would be a lot easier for me to troubleshoot. (I'm just hesitant to add the guard clause that you proposed without knowing how the bug is happening.)

**Comment by antprogSmith** [comment] 2017-11-30 06:57
Here is the code for that module.



'use strict';

/**
 * Wraps Prometheus client - https://github.com/siimon/prom-client
 * Goal: use metrics in any file of your app without harm
 * 
 * Taken from and adapted: https://github.com/iadvize/nodejs-prometheus-wrapper
 */

const client = require('prom-client');
const AggregatorRegistry = client.AggregatorRegistry;
const aggregatorRegistry = new AggregatorRegistry();

const references = {};
var namespace = '';

module.exports = {
	/**
	 * Sets a namespace for all the metrics created after its call
	 * @param ns
	 */
	setNamespace: function (ns) {
		namespace = ns;
	},

	getClient: function () {
		return client;
	},

	/**
	 * What to expose in /metrics in your server
	 */
	getMetrics: function () {
		return client.register.metrics();
	},

	getClusterMetrics: function () {
		return new Promise(function(resolve, reject) {
            aggregatorRegistry.clusterMetrics((err, metrics) => {
                if (err) reject(err);
                resolve(metrics);
            });
		});
	},

	/**
	 * Get metric by its name
	 * @param name
	 * @returns {*}
	 */
	get: function (name) {
		return references[name];
	},

	createCounter: function (name, help, labelNames = []) {
		references[name] = new client.Counter({name : namespace + '_' + name, help, labelNames});
		return references[name];
	},

	createGauge: function (name, help, labelNames = []) {
		references[name] = new client.Gauge({name : namespace + '_' + name, help, labelNames});
		return references[name];
	},

	createHistogram: function (name, help, buckets, labelNames = []) {
		references[name] = new client.Histogram({name : namespace + '_' + name, help, labelNames, buckets});
		return references[name];
	},

	createSummary: function (name, help, buckets, labelNames = []) {
		references[name] = new client.Summary({name : namespace + '_' + name, help, labelNames, buckets});
		return references[name];
	}
};

**Comment by zbjornson** [comment] 2018-03-29 01:28
Without a simple way to reproduce this, I can't really help any further here. Might want to close this issue.

**Closed** 2018-03-29 13:08 UTC
Labels: question

**Comment by lfender6445** [comment] 2018-07-06 00:50
I just wanted to note for other people, this issue only occurred for me when i was using symkinked packages with `yarn link`, where i was getting an additional request outside the number of CPUs 

while i dont fully understand the issue, i can say it disappeared for me when I manually built the dependency inside of my project.

**Comment by zbjornson** [comment] 2018-07-06 00:54
Ohh, that could definitely make sense...

With that I can try to repro it and make it non-fatal.
