### ISSUE TITLE
node does not exit

### ISSUE THREAD

**Issue by y0y0z** [siimon/prom-client#369] opened 2020-05-04 06:23 UTC
i use prom-client version 12.0.0.

when i run `jest --detectOpenHandles` i get

```shell
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  ELDHISTOGRAM

      3 | const client = require("prom-client");
      4 | const prefix = "name_";
    > 5 | client.collectDefaultMetrics({ prefix });
```

following [not returning an interval](https://github.com/siimon/prom-client/issues/342), i saw the [docs update](https://github.com/siimon/prom-client/pull/353/files/aa4b6cfb38877e962435826de9e4dce52ee18fad). also looked at the tests and saw that indeed [`clearInterval()`](https://github.com/siimon/prom-client/blob/master/test/defaultMetricsTest.js#L55) is called.

could one please shed the light on how should prom-client be closeed properly?

**Comment by zbjornson** [comment] 2020-05-06 16:09
I think we need to be [disabling the event loop delay histogram](https://nodejs.org/dist/latest-v12.x/docs/api/perf_hooks.html#perf_hooks_histogram_disable) in an exit handler...

**Comment by sam-github** [comment] 2020-05-06 16:53
It should be unrefed, best to avoid exit handlers, except it doesn't appear to have a documented unref. It might be there anyway, I'll go look.

subject should be fixed, "exists" was meant to be "exit", I think.

**Comment by sam-github** [comment] 2020-05-06 17:04
This is a false-positive on the part of jest, I can't reproduce a scenario where node does not exit, either by calling the default collector, or by call perf_hooks.

@y0y0z  can you provide a reproduction of failure to exit?

This may be a bug that should be reported to jest.

**Comment by sam-github** [comment] 2020-05-06 17:10
Also, note that while the tests are calling `clearInterval()`, this is either legacy code to be deleted, or possibly, a check of backward compatibility of the API.  The so-called interval in `interval = collectDefaultMetrics()` is now always `undefined` (no interval timer is used anymore).

**Comment by y0y0z** [comment] 2020-05-10 08:42
> Also, note that while the tests are calling `clearInterval()`, this is either legacy code to be deleted, or possibly, a check of backward compatibility of the API. The so-called interval in `interval = collectDefaultMetrics()` is now always `undefined` (no interval timer is used anymore).

@sam-github: https://github.com/siimon/prom-client/issues/342

indeed the tests are for the old implementation and does not coincide with the issue #342.

currently, i do not have a repository to reproduce the issue, will try my best to share something later on. meanwhile, i think revising the current test and fix them to reflect the changes, might reveal the issue.

**Comment by sam-github** [comment] 2020-05-10 14:57
Removing those lines from the tests doesn't change jest's opinion about whether prom-client is leaking handles. If there is no problem with prom-client (and I can't find one), then the issue should be closed and opened against jest.

**Comment by SimenB** [comment] 2020-05-11 12:50
Jest should not count `ELDHISTOGRAM` or `PerformanceObserver`. They don't keep the process open, so Jest shouldn't care about them.

Wanna send a PR? Code is here: https://github.com/facebook/jest/blob/0e0eeed9d794fe0d6d7e84f555d9684f9e944221/packages/jest-core/src/collectHandles.ts#L55-L57

If you don't have time to send a PR, could you open up an issue?

(I'm one of the maintainers of Jest).

**Comment by y0y0z** [comment] 2020-05-11 13:26
@SimenB: **thank you**. i opened an issue.

**Comment by SimenB** [comment] 2020-05-11 14:30
Thanks!

**Closed by SimenB** 2020-05-11 14:30 UTC

**Comment by micaelmbagira** [comment] 2021-02-26 12:40
@SimenB MR is open https://github.com/facebook/jest/pull/11123
