### ISSUE TITLE
no data on startup

### ISSUE THREAD

**Issue by tcurdt** [siimon/prom-client#438] opened 2021-04-28 01:01 UTC
I am registering the client as per documentation. I can query the `/metrics` endpoint just fine.
Unfortunately the counters don't have initial values for my custom metrics.

```
# HELP foo testing counter
# TYPE foo counter

# HELP process_heap_bytes Process heap size in bytes.
# TYPE process_heap_bytes gauge
process_heap_bytes 128987136
```

While the `collectDefaultMetrics` seems to be doing fine it seems I first have to increase the counters to provide any data at all. Which isn't particular great for alerting.

```
const prometheus = require('prom-client')
const { Counter } = prometheus

const foo = new Counter({
    name: 'foo',
    help: 'foo testing counter',
    labelNames: ['result']
})
```

Do I really have to set the counters to zero on startup manually?
I feel like I must be missing something.

**Comment by tcurdt** [comment] 2021-04-28 01:13
I just realized this is because of the label - which is fair.
But while setting a gauge to 0 is no problem - how does one initialize a counter to 0? `inc(0)`?

**Comment by tcurdt** [comment] 2021-04-28 01:20
This feels like a hack but seems to work:

```
foo.inc({ result: 'success'}, 0)
```

**Comment by zbjornson** [comment] 2021-09-19 17:53
`foo.inc(labels, 0)` is the best option for now (that's a supported usage with tests). Closing as a duplicate of #233 -- see discussion there and the guidance at https://prometheus.io/docs/practices/instrumentation/#avoid-missing-metrics (which suggests that users should be manually zeroing these values when known to exist).

**Closed by zbjornson** 2021-09-19 17:53 UTC
