### ISSUE TITLE
Always registering global event handlers causes issues with multiple require('prom-client').

### ISSUE THREAD

**Issue by ottomata** [siimon/prom-client#450] opened 2021-07-15 14:51 UTC
I don't fully understand this problem, but as reported in https://github.com/siimon/prom-client/issues/199#issuecomment-556908200, multiple requires of prom-client when used in cluster mode causes AggregatorRegistry to throw `TypeError: Cannot read property 'responses' of undefined`.

I encountered this when trying to use [node-rdkafka-prometheus](https://github.com/Collaborne/node-rdkafka-prometheus) with an express app that also used prom-client to expose its own metrics.  I'm avoiding the error by modifying node-rdkafka-prometheus to itself [accept the prom-client export](https://github.com/wikimedia/node-rdkafka-prometheus/pull/1/commits/302945a92b71e7ed888aea1aa76f1c5fe3e45725) so that it may be passed in directly from the application.

This is pretty hacky workaround.  It seems to me that just a `require('prom-client')` shouldn't affect globals.  Instead, event handlers and global registries should be explicitly set up in a dedicated prometheus client / registry of some kind.  Something like

```javascript
const promClient = require('prom-client');
const prometheus = promClient.getInstance();
```
Or something.

No global variables or event handlers would be registered, instead globals and handlers would be contained and specific for a prom client instance.

Since I don't fully understand the problem I could be wrong, but this may be related to these issues too: #199 #448 #265 #181

**Comment by zbjornson** [comment] 2021-07-15 15:53
Yeah, this is a duplicate of #448. There's a PR already to fix it that is just about ready to land, hope to finish reviewing it this weekend.

**Closed by zbjornson** 2021-07-15 15:53 UTC

**Comment by ottomata** [comment] 2021-07-15 16:21
Oh that's good to hear!  Thank you!
