### ISSUE TITLE
Possible `zero` method for counters

### ISSUE THREAD

**Issue by samarara** [siimon/prom-client#455] opened 2021-08-11 16:36 UTC
Currently, histograms have zero methods that can initialize the value to zero for a given labelset. Is it worth imploring this for counters as well? When counters are not initialized to zero, aggregate function like `rate` and `increase` don't work appropriately.

**Comment by zbjornson** [comment] 2021-09-19 17:50
There's more on this in #233 and #438. Counters and Gauges are easy to set to 0 meanwhile:

```
counter.inc({label1: "value1"}, 0)
gauge.set({label1: "value1"}, 0)
```

Going to mark as a duplicate of #233 since there's the most discussion there.

**Closed by zbjornson** 2021-09-19 17:50 UTC
