### ISSUE TITLE
labels() does not accept objects as described in README

### ISSUE THREAD

**Issue by ckpwong** [siimon/prom-client#431] opened 2021-03-23 16:05 UTC
In README, `gauge.labels({label1: value1, label2: value2}).set(1)` is supposed to be valid (as 2nd version), but it is rejected in util.js `getLabels()` because it expects args to be an array. Same case for `histogram.labels()` and `summary.labels()`.

`counter.labels()` has slightly different implementation than the rest, but getLabels() would still throw `Error`.

Please either change the README to not show that as a valid example, or change the code to implement this.

**Comment by zbjornson** [comment] 2021-09-19 00:58
I can't reproduce this issue, all three of the examples under **Labels** in the readme work. Which version of prom-client are you using? This feature was added in v13.1.0.

**Comment by zbjornson** [comment] 2022-08-25 21:28
Closing without more info.

**Closed by zbjornson** 2022-08-25 21:28 UTC
Labels: needs more info

**Comment by cslovell** [comment] 2023-01-18 20:59
Fantastic repo by the way - but just for the record this is still an issue. I've got `"prom-client": "^14.1.1"` in package.json and I get the following error hint in VS Code. Hope this helps somewhat.

```
o overload matches this call.
  Overload 1 of 2, '(...values: string[]): Internal<"code">', gave the following error.
    Argument of type '{ method: string; statusCode: string; }' is not assignable to parameter of type 'string'.
  Overload 2 of 2, '(labels: Partial<Record<"code", string | number>>): Internal<"code">', gave the following error.
    Argument of type '{ method: string; statusCode: string; }' is not assignable to parameter of type 'Partial<Record<"code", string | number>>'.
      Object literal may only specify known properties, and 'method' does not exist in type 'Partial<Record<"code", string | number>>'.ts(2769)
```
